"""test migration

Revision ID: 31c11f74426c
Revises: b0c70cfff473
Create Date: 2026-07-28 14:08:35.190604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c11f74426c'
down_revision: Union[str, None] = 'b0c70cfff473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Удаляем таблицы, которые зависят от других (дочерние)
    op.drop_table('favorites')       # зависит от users и ads
    op.drop_table('ad_categories')   # зависит от ads и categories
    op.drop_table('ads')             # зависит от partners и categories
    op.drop_table('categories')      # на нее ссылается ads
    op.drop_table('partners')        # на нее ссылается ads
    
    # Удаляем независимые таблицы
    op.drop_index('ix_partner_requests_id', table_name='partner_requests')
    op.drop_table('partner_requests')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_categories',
    sa.Column('ad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name='ad_categories_ad_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='ad_categories_category_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ad_id', 'category_id', name='ad_categories_pkey')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ads_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('partner_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('clicks_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('emodzi_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prioritet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['partner_email'], ['partners.user_email'], name='ads_partner_email_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ads_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_ads_id', 'ads', ['id'], unique=False)
    op.create_table('partner_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_person', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='partnerrequeststatus'), autoincrement=False, nullable=True),
    sa.Column('admin_comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='partner_requests_pkey')
    )
    op.create_index('ix_partner_requests_id', 'partner_requests', ['id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name='favorites_ad_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='favorites_user_email_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.create_index('ix_favorites_id', 'favorites', ['id'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ads_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='partners_user_email_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='partners_pkey'),
    sa.UniqueConstraint('user_email', name='partners_user_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_partners_id', 'partners', ['id'], unique=False)
    # ### end Alembic commands ###
