"""clinics_coordinates

Revision ID: 4e349b2b7f44
Revises: eb3997ec001d
Create Date: 2026-09-03 11:41:48.156494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4e349b2b7f44"
down_revision: Union[str, None] = "eb3997ec001d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clinics", sa.Column("coordinates", sa.String(length=100), nullable=False)
    )
    op.drop_column("clinics", "location_url")


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clinics",
        sa.Column(
            "location_url", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("clinics", "coordinates")
    # ### end Alembic commands ###
