"""add_status_to_patients

Revision ID: 7eef4b5fae5c
Revises: eeb75508a0e2
Create Date: 2026-09-01 17:42:52.397783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7eef4b5fae5c"
down_revision: Union[str, None] = "eeb75508a0e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patients", sa.Column("status", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "status")
    # ### end Alembic commands ###
