"""fix bugs

Revision ID: a9c8667245f8
Revises: 4e349b2b7f44
Create Date: 2026-09-14 14:55:03.256928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c8667245f8'
down_revision: Union[str, None] = '4e349b2b7f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('column_order', sa.JSON(), nullable=True))
    op.add_column('referrals', sa.Column('status_changed_at', sa.DateTime(), nullable=True))
    op.add_column('referrals', sa.Column('commission_amount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('referrals', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'is_paid')
    op.drop_column('referrals', 'commission_amount')
    op.drop_column('referrals', 'status_changed_at')
    op.drop_column('doctors', 'column_order')
    # ### end Alembic commands ###
