"""gender

Revision ID: af67ab719462
Revises: 7eef4b5fae5c
Create Date: 2026-09-01 17:56:00.394678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "af67ab719462"
down_revision: Union[str, None] = "7eef4b5fae5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patients",
        "gender",
        existing_type=sa.VARCHAR(length=1),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patients",
        "gender",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
