"""remove patient_email unique

Revision ID: eb3997ec001d
Revises: af67ab719462
Create Date: 2026-09-03 10:59:15.119782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "eb3997ec001d"
down_revision: Union[str, None] = "af67ab719462"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("patients_email_key", "patients", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "patients_email_key", "patients", ["email"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
