"""Описание изменений

Revision ID: eeb75508a0e2
Revises: 6e7f57f74f06
Create Date: 2026-09-01 09:03:20.739504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb75508a0e2'
down_revision: Union[str, None] = '6e7f57f74f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('education', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'education')
    # ### end Alembic commands ###
